# 单文件编排，兼容旧版 docker-compose
version: "3.8"

services:
  mysql:
    privileged: true
    image: mysql:5.7
    restart: always
    env_file: .env
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-o5KjnPYxswsiURZHCPwd}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-skyway}
      MYSQL_USER: ${MYSQL_USER:-skyway}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-o5KjnPYxswsiURZHCPwd}
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/database/mysql/data:/var/lib/mysql
      - ./volumes/database/mysql/conf.d:/etc/mysql/conf.d
      - ./volumes/database/mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","127.0.0.1","-po5KjnPYxswsiURZHCPwd" ]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 1200s
    networks:
      - skyway_net

  redis:
    image: redis:6-alpine
    restart: always
    env_file: .env
    environment:
      REDISCLI_AUTH: ${REDIS_PASSWORD:-J98%FHF#9h@e88h9fre9}
    volumes:
      - ./volumes/redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-J98%FHF#9h@e88h9fre9}
    ports:
      - "${EXPOSE_REDIS_PORT:-6379}:6379"
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
    networks:
      - skyway_net

  skyway-admin:
    image: crpi-kf13onfj0v8f6jax.cn-shanghai.personal.cr.aliyuncs.com/ming121/skyway-admin:latest
    restart: always
    env_file: .env
    environment:
      TZ: Asia/Shanghai
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/
      MYSQL_DATABASE: ${MYSQL_DATABASE:-skyway}
      MYSQL_USER: ${MYSQL_USER:-skyway}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-o5KjnPYxswsiURZHCPwd}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-J98%FHF#9h@e88h9fre9}
    command: ["--spring.profiles.active=prod", "--spring.config.additional-location=file:/app/config/"]
    volumes:
      - ./volumes/skyway/config:/app/config:ro
      - ./volumes/skyway/logs:/app/logs
      - ./volumes/skyway/upload:/app/upload
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - skyway_net

  nginx:
    image: nginx:1.24-alpine
    restart: always
    env_file: .env
    ports:
      - "${EXPOSE_NGINX_PORT:-8081}:8081"
      - "${EXPOSE_NGINX_C_PORT:-8082}:8082"
    depends_on:
      - skyway-admin
    networks:
      - skyway_net
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/nginx/sites:/etc/nginx/http_vhost:ro
      - ./volumes/nginx/admin:/usr/share/nginx/admin:ro
      - ./volumes/nginx/c:/usr/share/nginx/c:ro
      - ./volumes/nginx/logs:/var/log/nginx

networks:
  skyway_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
